### ISSUE TITLE
about computing MMADE and MMFDE

### ISSUE THREAD

**Issue by yz-cnsdqz** [Khrylx/DLow#2]
Dear authors,

Many thanks for sharing code of this very nice work! I have some questions about these two metrics, and wish for some further explanation. 

In the function ```def get_multimodal_gt():```, could you please explain a bit more about it? Especially, what is the specific meaning of the threshold based on ```pd```? I could not fully understand what the physical meaning of ```pd``` is. 

Moreover, in the function ```compute_mmade()```, why the gt_dist is the mean value, rather than a min value like in ```compute_ade()```? 

Many thanks for your supports~!

**Comment by Khrylx** [comment]
Hello,

More information about MMADE and MMFDE can be found in the metrics section of https://arxiv.org/pdf/1907.04967.pdf.

Suppose there are N data samples {(c_i, x_i)}_i^N in the dataset, where c_i is past motion, x_i is future motion. MMADE/MMFDE basically augment each data example (c_i, x_i) by producing multiple future motions (c_i, {x_j}_j^M) where x_j is selected when ||c_i - c_j|| < threshold. The intuition is that data examples with similar past motions should share their future motions.

In the function `get_multimodal_gt`, `pd = squareform(pdist(all_start_pose))` computes the pairwise distance between past motions, i.e., `pd` is a 2D array where `pd[i][j]` stores ||c_i - c_j||. And by `ind = np.nonzero(pd[i] < args.multimodal_threshold)` we find all indices j that satisfy  ||c_i - c_j|| < threshold.

In the inner loop of `compute_mmade` (https://github.com/Khrylx/DLow/blob/master/motion_pred/eval.py#L113), we are calling `compute_ade` to evaluate the ade for each future motion x_j which is still computing the min dist. The mean is averaging over the ADE for each x_j. It doesn't make sense to use the min over x_j because we want the samples to cover all x_j, not just one of them.

Hope this answers your questions.

**Comment by yz-cnsdqz** [comment]
thanks a lot! this is very helpful.
